### ISSUE TITLE
docker compose fails

### ISSUE THREAD

**Issue by janrenz** [schul-cloud/cui#3] opened 2018-07-26 09:23 UTC
frisch vom Master:
```
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ca-certificates-java : Depends: openjdk-7-jre-headless but it is not installable or
                                 java7-runtime-headless
 openjdk-8-jdk : Depends: openjdk-8-jre (= 8u171-b11-1~bpo8+1) but it is not going to be installed
                 Depends: openjdk-8-jdk-headless (= 8u171-b11-1~bpo8+1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
ERROR: Service 'rasa-nlu' failed to build: The command '/bin/bash -c set -ex; 	if [ ! -d /usr/share/man/man1 ]; then 		mkdir -p /usr/share/man/man1; 	fi; 	apt-get update; 	apt-get install -y -t jessie-backports		openjdk-8-jdk 		ca-certificates-java 	; 	rm -rf /var/lib/apt/lists/*; 	[ "$(readlink -f "$JAVA_HOME")" = "$(docker-java-home)" ]; 	update-alternatives --get-selections | awk -v home="$(readlink -f "$JAVA_HOME")" 'index($3, home) == 1 { $2 = "manual"; print | "update-alternatives --set-selections" }'; 	update-alternatives --query java | grep -q 'Status: manual'' returned a non-zero code: 100
```

**Comment by felixmusmann** [comment] 2018-07-27 13:26
I can't reproduce this. 🤔 
@threxx Do you have this problem?

**Comment by felixmusmann** [comment] 2018-07-28 08:50
Fixed with https://github.com/schul-cloud/cui/commit/27c5627d9fa705b8012efdd6ac3c33b96a4cebf7

**Closed as completed by felixmusmann** 2018-07-28 08:50 UTC
